// contractABIs.js

const contractABIs = {
    // Contract 1
      stakeABI: [
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"_stETH",
                  "type":"address"
               },
               {
                  "internalType":"address",
                  "name":"_want",
                  "type":"address"
               }
            ],
            "stateMutability":"nonpayable",
            "type":"constructor"
         },
         {
            "anonymous":false,
            "inputs":[
               {
                  "indexed":true,
                  "internalType":"address",
                  "name":"previousOwner",
                  "type":"address"
               },
               {
                  "indexed":true,
                  "internalType":"address",
                  "name":"newOwner",
                  "type":"address"
               }
            ],
            "name":"OwnershipTransferred",
            "type":"event"
         },
         {
            "anonymous":false,
            "inputs":[
               {
                  "indexed":false,
                  "internalType":"address",
                  "name":"_user",
                  "type":"address"
               },
               {
                  "indexed":false,
                  "internalType":"uint256",
                  "name":"_amount",
                  "type":"uint256"
               }
            ],
            "name":"onSubmit",
            "type":"event"
         },
         {
            "inputs":[
               
            ],
            "name":"accWantPerShare",
            "outputs":[
               {
                  "internalType":"uint256",
                  "name":"",
                  "type":"uint256"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"calculationRewardBlock",
            "outputs":[
               {
                  "internalType":"uint256",
                  "name":"",
                  "type":"uint256"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"getTotalRewardPerDay",
            "outputs":[
               {
                  "internalType":"uint256",
                  "name":"_rewardPerDay",
                  "type":"uint256"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"_user",
                  "type":"address"
               }
            ],
            "name":"harvest",
            "outputs":[
               
            ],
            "stateMutability":"nonpayable",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"lastBalance",
            "outputs":[
               {
                  "internalType":"uint256",
                  "name":"",
                  "type":"uint256"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"lastCaculationReward",
            "outputs":[
               {
                  "internalType":"uint256",
                  "name":"",
                  "type":"uint256"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"",
                  "type":"address"
               }
            ],
            "name":"lastTimeSubmitOf",
            "outputs":[
               {
                  "internalType":"uint256",
                  "name":"",
                  "type":"uint256"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"miningMachine",
            "outputs":[
               {
                  "internalType":"contract IMiningMachine",
                  "name":"",
                  "type":"address"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"owner",
            "outputs":[
               {
                  "internalType":"address",
                  "name":"",
                  "type":"address"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"_user",
                  "type":"address"
               }
            ],
            "name":"pendingReward",
            "outputs":[
               {
                  "internalType":"uint256",
                  "name":"_pendingWant",
                  "type":"uint256"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"periodOfDay",
            "outputs":[
               {
                  "internalType":"uint256",
                  "name":"",
                  "type":"uint256"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"pidOfMining",
            "outputs":[
               {
                  "internalType":"uint256",
                  "name":"",
                  "type":"uint256"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"receiverShareOf",
            "outputs":[
               {
                  "internalType":"address",
                  "name":"",
                  "type":"address"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"renounceOwnership",
            "outputs":[
               
            ],
            "stateMutability":"nonpayable",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"",
                  "type":"address"
               }
            ],
            "name":"rewardWantDebtOf",
            "outputs":[
               {
                  "internalType":"uint256",
                  "name":"",
                  "type":"uint256"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"uint256",
                  "name":"_quantityBlock",
                  "type":"uint256"
               }
            ],
            "name":"setCalculationRewardBlock",
            "outputs":[
               
            ],
            "stateMutability":"nonpayable",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"_miningMachine",
                  "type":"address"
               }
            ],
            "name":"setMiningMachine",
            "outputs":[
               
            ],
            "stateMutability":"nonpayable",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"uint256",
                  "name":"_pid",
                  "type":"uint256"
               }
            ],
            "name":"setPidOfMining",
            "outputs":[
               
            ],
            "stateMutability":"nonpayable",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"_receiver",
                  "type":"address"
               }
            ],
            "name":"setReceiverShareOf",
            "outputs":[
               
            ],
            "stateMutability":"nonpayable",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"uint256",
                  "name":"_time",
                  "type":"uint256"
               }
            ],
            "name":"setTimeUnlockWithdraw",
            "outputs":[
               
            ],
            "stateMutability":"nonpayable",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"uint256",
                  "name":"_time",
                  "type":"uint256"
               }
            ],
            "name":"setTimeUnlockWithdrawReward",
            "outputs":[
               
            ],
            "stateMutability":"nonpayable",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"_want",
                  "type":"address"
               }
            ],
            "name":"setWantToken",
            "outputs":[
               
            ],
            "stateMutability":"nonpayable",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"",
                  "type":"address"
               }
            ],
            "name":"shareOf",
            "outputs":[
               {
                  "internalType":"uint256",
                  "name":"",
                  "type":"uint256"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"",
                  "type":"address"
               }
            ],
            "name":"shareOfLocked",
            "outputs":[
               {
                  "internalType":"uint256",
                  "name":"",
                  "type":"uint256"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"stETH",
            "outputs":[
               {
                  "internalType":"contract IstETH",
                  "name":"",
                  "type":"address"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"_referral",
                  "type":"address"
               }
            ],
            "name":"submit",
            "outputs":[
               
            ],
            "stateMutability":"payable",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"timeOfHarvest",
            "outputs":[
               {
                  "internalType":"uint256",
                  "name":"",
                  "type":"uint256"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"timeUnlock",
            "outputs":[
               {
                  "internalType":"uint256",
                  "name":"",
                  "type":"uint256"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"timeUnlockWithdrawReward",
            "outputs":[
               {
                  "internalType":"uint256",
                  "name":"",
                  "type":"uint256"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"totalShare",
            "outputs":[
               {
                  "internalType":"uint256",
                  "name":"",
                  "type":"uint256"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"newOwner",
                  "type":"address"
               }
            ],
            "name":"transferOwnership",
            "outputs":[
               
            ],
            "stateMutability":"nonpayable",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"_user",
                  "type":"address"
               }
            ],
            "name":"userInfo",
            "outputs":[
               {
                  "internalType":"uint256[14]",
                  "name":"data",
                  "type":"uint256[14]"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"want",
            "outputs":[
               {
                  "internalType":"contract IERC20",
                  "name":"",
                  "type":"address"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"uint256",
                  "name":"_wantAmt",
                  "type":"uint256"
               }
            ],
            "name":"withdraw",
            "outputs":[
               
            ],
            "stateMutability":"nonpayable",
            "type":"function"
         }
      ],
      erc20ABI : [
         {
            "inputs":[
               
            ],
            "stateMutability":"nonpayable",
            "type":"constructor"
         },
         {
            "anonymous":false,
            "inputs":[
               {
                  "indexed":true,
                  "internalType":"address",
                  "name":"owner",
                  "type":"address"
               },
               {
                  "indexed":true,
                  "internalType":"address",
                  "name":"spender",
                  "type":"address"
               },
               {
                  "indexed":false,
                  "internalType":"uint256",
                  "name":"value",
                  "type":"uint256"
               }
            ],
            "name":"Approval",
            "type":"event"
         },
         {
            "anonymous":false,
            "inputs":[
               {
                  "indexed":true,
                  "internalType":"address",
                  "name":"previousOwner",
                  "type":"address"
               },
               {
                  "indexed":true,
                  "internalType":"address",
                  "name":"newOwner",
                  "type":"address"
               }
            ],
            "name":"OwnershipTransferred",
            "type":"event"
         },
         {
            "anonymous":false,
            "inputs":[
               {
                  "indexed":true,
                  "internalType":"address",
                  "name":"from",
                  "type":"address"
               },
               {
                  "indexed":true,
                  "internalType":"address",
                  "name":"to",
                  "type":"address"
               },
               {
                  "indexed":false,
                  "internalType":"uint256",
                  "name":"value",
                  "type":"uint256"
               }
            ],
            "name":"Transfer",
            "type":"event"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"owner",
                  "type":"address"
               },
               {
                  "internalType":"address",
                  "name":"spender",
                  "type":"address"
               }
            ],
            "name":"allowance",
            "outputs":[
               {
                  "internalType":"uint256",
                  "name":"",
                  "type":"uint256"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"spender",
                  "type":"address"
               },
               {
                  "internalType":"uint256",
                  "name":"amount",
                  "type":"uint256"
               }
            ],
            "name":"approve",
            "outputs":[
               {
                  "internalType":"bool",
                  "name":"",
                  "type":"bool"
               }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"account",
                  "type":"address"
               }
            ],
            "name":"balanceOf",
            "outputs":[
               {
                  "internalType":"uint256",
                  "name":"",
                  "type":"uint256"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"decimals",
            "outputs":[
               {
                  "internalType":"uint8",
                  "name":"",
                  "type":"uint8"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"spender",
                  "type":"address"
               },
               {
                  "internalType":"uint256",
                  "name":"subtractedValue",
                  "type":"uint256"
               }
            ],
            "name":"decreaseAllowance",
            "outputs":[
               {
                  "internalType":"bool",
                  "name":"",
                  "type":"bool"
               }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"spender",
                  "type":"address"
               },
               {
                  "internalType":"uint256",
                  "name":"addedValue",
                  "type":"uint256"
               }
            ],
            "name":"increaseAllowance",
            "outputs":[
               {
                  "internalType":"bool",
                  "name":"",
                  "type":"bool"
               }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"_user",
                  "type":"address"
               },
               {
                  "internalType":"uint256",
                  "name":"_amount",
                  "type":"uint256"
               }
            ],
            "name":"mintReward",
            "outputs":[
               
            ],
            "stateMutability":"nonpayable",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"name",
            "outputs":[
               {
                  "internalType":"string",
                  "name":"",
                  "type":"string"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"owner",
            "outputs":[
               {
                  "internalType":"address",
                  "name":"",
                  "type":"address"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"renounceOwnership",
            "outputs":[
               
            ],
            "stateMutability":"nonpayable",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"_referral",
                  "type":"address"
               }
            ],
            "name":"submit",
            "outputs":[
               
            ],
            "stateMutability":"payable",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"symbol",
            "outputs":[
               {
                  "internalType":"string",
                  "name":"",
                  "type":"string"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"totalSupply",
            "outputs":[
               {
                  "internalType":"uint256",
                  "name":"",
                  "type":"uint256"
               }
            ],
            "stateMutability":"view",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"to",
                  "type":"address"
               },
               {
                  "internalType":"uint256",
                  "name":"amount",
                  "type":"uint256"
               }
            ],
            "name":"transfer",
            "outputs":[
               {
                  "internalType":"bool",
                  "name":"",
                  "type":"bool"
               }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"from",
                  "type":"address"
               },
               {
                  "internalType":"address",
                  "name":"to",
                  "type":"address"
               },
               {
                  "internalType":"uint256",
                  "name":"amount",
                  "type":"uint256"
               }
            ],
            "name":"transferFrom",
            "outputs":[
               {
                  "internalType":"bool",
                  "name":"",
                  "type":"bool"
               }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
         },
         {
            "inputs":[
               {
                  "internalType":"address",
                  "name":"newOwner",
                  "type":"address"
               }
            ],
            "name":"transferOwnership",
            "outputs":[
               
            ],
            "stateMutability":"nonpayable",
            "type":"function"
         },
         {
            "inputs":[
               
            ],
            "name":"widthdrawETH",
            "outputs":[
               
            ],
            "stateMutability":"nonpayable",
            "type":"function"
         }
      ],

};

export default contractABIs;