// contractABIs.js

const contractABIs = {
    // Contract 1
    stakeABI: [
        {
           "inputs":[
              {
                 "internalType":"address",
                 "name":"_stETH",
                 "type":"address"
              }
           ],
           "stateMutability":"nonpayable",
           "type":"constructor"
        },
        {
           "anonymous":false,
           "inputs":[
              {
                 "indexed":true,
                 "internalType":"address",
                 "name":"previousOwner",
                 "type":"address"
              },
              {
                 "indexed":true,
                 "internalType":"address",
                 "name":"newOwner",
                 "type":"address"
              }
           ],
           "name":"OwnershipTransferred",
           "type":"event"
        },
        {
           "anonymous":false,
           "inputs":[
              {
                 "indexed":false,
                 "internalType":"address",
                 "name":"_user",
                 "type":"address"
              },
              {
                 "indexed":false,
                 "internalType":"uint256",
                 "name":"_amount",
                 "type":"uint256"
              }
           ],
           "name":"onSubmit",
           "type":"event"
        },
        {
           "inputs":[
              
           ],
           "name":"accWantPerShare",
           "outputs":[
              {
                 "internalType":"uint256",
                 "name":"",
                 "type":"uint256"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              
           ],
           "name":"getTotalRewardPerDay",
           "outputs":[
              {
                 "internalType":"uint256",
                 "name":"_rewardPerDay",
                 "type":"uint256"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"address",
                 "name":"_user",
                 "type":"address"
              }
           ],
           "name":"harvest",
           "outputs":[
              
           ],
           "stateMutability":"nonpayable",
           "type":"function"
        },
        {
           "inputs":[
              
           ],
           "name":"lastBalance",
           "outputs":[
              {
                 "internalType":"uint256",
                 "name":"",
                 "type":"uint256"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              
           ],
           "name":"owner",
           "outputs":[
              {
                 "internalType":"address",
                 "name":"",
                 "type":"address"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"address",
                 "name":"_user",
                 "type":"address"
              }
           ],
           "name":"pendingReward",
           "outputs":[
              {
                 "internalType":"uint256",
                 "name":"_pendingWant",
                 "type":"uint256"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              
           ],
           "name":"periodOfDay",
           "outputs":[
              {
                 "internalType":"uint256",
                 "name":"",
                 "type":"uint256"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              
           ],
           "name":"renounceOwnership",
           "outputs":[
              
           ],
           "stateMutability":"nonpayable",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"address",
                 "name":"",
                 "type":"address"
              }
           ],
           "name":"rewardWantDebtOf",
           "outputs":[
              {
                 "internalType":"uint256",
                 "name":"",
                 "type":"uint256"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"address",
                 "name":"",
                 "type":"address"
              }
           ],
           "name":"shareOf",
           "outputs":[
              {
                 "internalType":"uint256",
                 "name":"",
                 "type":"uint256"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              
           ],
           "name":"stETH",
           "outputs":[
              {
                 "internalType":"contract IstETH",
                 "name":"",
                 "type":"address"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"address",
                 "name":"_referral",
                 "type":"address"
              }
           ],
           "name":"submit",
           "outputs":[
              
           ],
           "stateMutability":"payable",
           "type":"function"
        },
        {
           "inputs":[
              
           ],
           "name":"timeOfHarvest",
           "outputs":[
              {
                 "internalType":"uint256",
                 "name":"",
                 "type":"uint256"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              
           ],
           "name":"totalShare",
           "outputs":[
              {
                 "internalType":"uint256",
                 "name":"",
                 "type":"uint256"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"address",
                 "name":"newOwner",
                 "type":"address"
              }
           ],
           "name":"transferOwnership",
           "outputs":[
              
           ],
           "stateMutability":"nonpayable",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"address",
                 "name":"_user",
                 "type":"address"
              }
           ],
           "name":"userInfo",
           "outputs":[
              {
                 "internalType":"uint256[7]",
                 "name":"data",
                 "type":"uint256[7]"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              
           ],
           "name":"version",
           "outputs":[
              {
                 "internalType":"uint256",
                 "name":"",
                 "type":"uint256"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"uint256",
                 "name":"_wantAmt",
                 "type":"uint256"
              }
           ],
           "name":"withdraw",
           "outputs":[
              
           ],
           "stateMutability":"nonpayable",
           "type":"function"
        }
     ],

  
  };
  
  export default contractABIs;
  